CREATE DATABASE VehicleSalesDB;
GO

USE VehicleSalesDB;
GO

CREATE TABLE Agency (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(255) NOT NULL,
    Location NVARCHAR(255) NOT NULL
);

CREATE TABLE Customer (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    FirstName NVARCHAR(100) NOT NULL,
    LastName NVARCHAR(100) NOT NULL,
    Email NVARCHAR(255) UNIQUE NOT NULL,
    Phone NVARCHAR(50) NOT NULL
);

CREATE TABLE Brand (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL
);

CREATE TABLE Vehicle (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    BrandId INT NOT NULL,
    Engine NVARCHAR(255) NOT NULL,
    Doors INT NOT NULL,
    FuelType NVARCHAR(100) NOT NULL,
    Accessories NVARCHAR(MAX) NULL,
    FOREIGN KEY (BrandId) REFERENCES Brand(Id) ON DELETE CASCADE
);

CREATE TABLE Sale (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    AgencyId INT NOT NULL,
    CustomerId INT NOT NULL,
    VehicleId INT NOT NULL UNIQUE,
    SaleDate DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (AgencyId) REFERENCES Agency(Id) ON DELETE CASCADE,
    FOREIGN KEY (CustomerId) REFERENCES Customer(Id) ON DELETE CASCADE,
    FOREIGN KEY (VehicleId) REFERENCES Vehicle(Id) ON DELETE CASCADE
);